project_id = "bzuhnpnhydizzitxeujo"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"

[functions.generate-audio-alert]
verify_jwt = false

[functions.fetch-weather]
verify_jwt = false

[functions.generate-demo-data]
verify_jwt = false

[functions.suggest-safe-route]
verify_jwt = false

[functions.get-navigation-route]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.telegram-alert]
verify_jwt = false
